export const Fall2024Speakers = [
  {
    date: "Sep 27",
    name: "Cindy Grimm",
    affiliation: "Oregon State University",
    title: "Robotics State of the Union Address",
    location: "Rogers Hall 230",
    time: "10:00am",
    url: "https://engineering.oregonstate.edu/people/cindy-grimm",
  },
  {
    date: "Oct 4",
    name: "Mark Yim",
    affiliation: "University of Pennsylvania",
    title: "TBD",
    location: "Rogers Hall 230",
    time: "10:00am",
    url: "https://www.grasp.upenn.edu/people/mark-yim/",
  },
  {
    date: "Oct 11",
    name: "Zach Beattie",
    affiliation: "Oregon Health and Science University",
    title: "TBD",
    location: "Rogers Hall 230",
    time: "10:00am",
    url: "https://www.ohsu.edu/people/zachary-beattie-phd",
  },
  {
    date: "Oct 18",
    name: "Melisa Orta Martinez",
    affiliation: "Carnegie Mellon University",
    title: "TBD",
    location: "Rogers Hall 230",
    time: "10:00am",
    url: "https://www.ri.cmu.edu/ri-faculty/melisa-orta-martinez/",
  },
  {
    date: "Oct 25",
    name: "Vy Nguyen",
    affiliation: "Hello Robot",
    title: "TBD",
    location: "Rogers Hall 230",
    time: "10:00am",
    url: "https://hello-robot.com/",
  },
  {
    date: "Nov 1",
    name: "Matthew Gombolay",
    affiliation: "Georgia Institute of Technology",
    title: "TBD",
    location: "Rogers Hall 230",
    time: "10:00am",
    url: "https://core-robotics.gatech.edu/people/matthew-gombolay/",
  },
  {
    date: "Nov 8",
    name: "Carina Buzo Tipton",
    affiliation: "Oregon State University",
    title: "TBD",
    location: "Rogers Hall 230",
    time: "10:00am",
  },
  {
    date: "Nov 15",
    name: "Brittany Duncan",
    affiliation: "University of Nebraska-Lincoln",
    title: "TBD",
    location: "Rogers Hall 230",
    time: "10:00am",
    url: "https://brittanyduncan.github.io/",
  },
  {
    date: "Nov 22",
    name: "Avik De",
    affiliation: "Ghost Robotics",
    title: "TBD",
    location: "Rogers Hall 230",
    time: "10:00am",
    url: "https://www.ghostrobotics.io/",
  },
  {
    date: "Dec 6",
    name: "Evan Ackerman",
    affiliation: "IEEE",
    title: "TBD",
    location: "Rogers Hall 230",
    time: "10:00am",
    url: "https://spectrum.ieee.org/u/evan-ackerman",
  },
];
