export const Spring2024Speakers = [
  {
    date: "Apr 5",
    name: "Kate Tsui",
    affiliation: "Toyota Research Institute",
    title: "Physical and Social Assistance for Aging Society",
    location: "Rogers Hall 230",
    time: "10:00am",
    url: "https://www.tri.global/about-us/dr-katherine-tsui",
  },
  {
    date: "Apr 12",
    name: "Matei Ciocarlie",
    affiliation: "Columbia University",
    title: "We (finally) have dexterous robotic manipulation. Now what?",
    location: "Rogers Hall 230",
    time: "10:00am",
    url: "https://roam.me.columbia.edu/people/matei-ciocarlie",
  },
  {
    date: "May 3",
    name: "Michael Gleicher",
    affiliation: "University of Wisconsin-Madison",
    title:
      "Ranged Kinematics and Time of Flight Sensors for Shared Autonomy Robotic Systems",
    location: "Rogers Hall 230",
    time: "10:00am",
    url: "https://gleicher.sites.cs.wisc.edu/",
  },
  {
    date: "May 10",
    name: "Nathan Kirchner",
    affiliation: "Workr Labs Inc.",
    title:
      "My name is Nathan & I think... interacting with robots is needlessly painful",
    location: "Rogers Hall 230",
    time: "10:00am",
    url: "https://www.linkedin.com/in/nkirchner",
  },
  {
    date: "May 24",
    name: "Dallas Swindle",
    affiliation: "Independent Artist",
    title: "Art at Scale: Making Big Things that Glow",
    location: "Rogers Hall 230",
    time: "10:00am",
    url: "http://dasivdesign.com/",
  },
  {
    date: "May 31",
    name: "Paul Robinette",
    affiliation: "UMass Lowell",
    title: "TBD",
    location: "Rogers Hall 230",
    time: "10:00am",
    url: "https://sites.uml.edu/paul-robinette/",
  },
];
